### ISSUE TITLE
Case class generation

### ISSUE THREAD

**Issue by BenFradet** [intenthq/sbt-thrift-plugin#11]
Hello, is there any plan to support case class generation like https://github.com/guardian/scrooge-code-gen-sbt-plugin ?

**Comment by nathankleyn** [comment]
@BenFradet For now we're focusing on Thrift only within this repo which means that we're limited to targets it can support.

Thrift cannot generate Scala targets yet so Scrooge exists as a separate backend to circumvent this.  Unfortunately, Scrooge only generates Scala, Java, Cocoa, Android and Lua which means we'd have to deprecate some of the targets we support in this library should we switch. Worse still, it looks as if [Thrift doesn't have any current plans to add support for Scala](https://issues.apache.org/jira/browse/THRIFT-1675), so no hope on that front either at the moment.

At this stage, we're holding out for Scala support in Thrift (maybe we or somebody else may contribute one upstream) - but given we make less use of Thrift than we used to within @intenthq we aren't finding ourselves in desperate need for it anyway so are just living with the Java bindings for now.

Hope this helps!
