### ISSUE TITLE
Non-JVM Languages Generators Should Return Empty Seq

### ISSUE THREAD

**Issue by mlvn23** [intenthq/sbt-thrift-plugin#5]
Otherwise, SBT would try to compile the non-JVM files.

See that the else has been commented out in https://github.com/bigtoast/sbt-thrift/blob/master/src/main/scala/ThriftPlugin.scala line 66.

```
thriftGenerateJs <<= (streams, thriftSourceDir, thriftJsOutputDir,
                          thrift, thriftJsOptions, thriftJsEnabled, cacheDirectory ) map {
          ( out, sdir, odir, tbin, opts, enabled, cache ) =>
          if (enabled)
            compileThrift(sdir,odir,tbin,"js",opts,out.log, cache / "thrift-js" );
          //else
            Seq[File]()
},
```

**Comment by janstenpickle** [comment]
Hi @mlvn23, thanks for raising this, I've just fixed it in the referenced PR. You should be able to use `1.0.4` shortly.

**Comment by mlvn23** [comment]
Thanks!
